version: "3.9"

x-common: &common
  image: ghcr.io/toupsy/wachplan-generator:latest
  pull_policy: always
  restart: unless-stopped
  volumes:
    - wachplan-data:/app/data
    - .:/app
    - /app/node_modules
  environment: &env
    MASTER_SECRET: "cNJqZimlDKRZdTSitVf4b7QllDWXE+FVGGPkhtwNbuw="
    SALT: "cpDzbABAbgU/soUiD2mKFQ=="
    SESSION_SECRET: "u8AWjZf1bkUTgbkQXiBb/Um48gbkRJcbHImxh+skqB4="

services:
  wachplan:
    <<: *common
    container_name: dlrg-wachplan
    ports:
      - "3000:3000"
    environment:
      <<: *env
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "changeme"

  wachplan-admin:
    <<: *common
    container_name: dlrg-wachplan-admin
    ports:
      - "3001:3001"
    environment:
      <<: *env
      ADMIN_PORT: "3001"
      COOKIE_SECURE: "true"
    command: node admin-server.js
    depends_on:
      - wachplan

volumes:
  wachplan-data:
